### ISSUE TITLE
Misc Advices/issues

### ISSUE THREAD

**Issue by Carreau** [kiasar/gutenberg_cleaner#1]
Set [python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) in setup.py if you are not compatible with all python versions.

Add `dist/` and `egg-info` to your `.gitignore` (they should likely not be in the repository.) , and the name of `.gitignore` is `.gitignore`, not `gitignore.gitignore`; 

Likely `.idea` should be in your [machine-global gitignore](https://stackoverflow.com/questions/7335420/global-git-ignore).

As for your Reddit/SO question.

Python use `__all__` (https://docs.python.org/3/tutorial/modules.html#importing-from-a-package) if you want to "hide" some object from a module. They are still accessible (there is not concept of "private" like in many other languages; there is a "convention" (in [pep8](https://www.python.org/dev/peps/pep-0008/)) that "private object should have a leading underscore.

**Comment by kiasar** [comment]
(this is my first comment on Github). thank you very much Carreau. you helped me a lot.
